# Utilisation de la dernière image Ubuntu comme base
FROM ubuntu:latest

# Mise à jour des dépôts APT et mise à niveau des logiciels
RUN apt-get update && apt-get upgrade -y

# Commande exécutée lors du démarrage du conteneur (format JSON)
CMD ["echo", "Hello, World!"]
